# Meta Data for SEO

## Homepage
title = "DexQL"
titleSeparator = "-"
titleAddition = "DexQL Documentation"

## Documentation
# docsVersion = "0.3"



# Footer
footer = "Check out <a class=\"text-muted\" href=\"https://dex.minibuilds.io/\">Dex</a>"

# Feed
copyRight = "Copyright (c) 2020-2021 Henk Verlinde"

[sections]
  sectionNav = ["docs", "guides"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
